### PR TITLE
implement local caching for prevent send request every time

### PR DESCRIPTION
**Pull request by graymind75**
class for check&save request body in local cache, once saved it's not send another request in the day, instead get data from local cache
it will improve the performance and save time

### CODE REVIEW

**Comment by Pouriya-Jahanbakhsh** [comment]
Great! I will test it for 2 days to see how it works.

**Comment by Pouriya-Jahanbakhsh** [comment]
I've added one more method `delete` in caching class and used it in code when we used cache and something bad happened.

**Comment by Pouriya-Jahanbakhsh** [comment]
Thank you again!

**Comment by graymind75** [comment]
you're welcome bro

**Pull request merged**
